name: RoamPlugin
version: ${project.version}
main: dev.giovalgas.roamplugin.RoamPlugin
api-version: 1.16
commands:
  roam:
    aliases: ["fc", "freecam"]
    usage: "/roam"
    description: "Changes the player gamemode to spectator"
softdepend: [Vault]